(defun deletein(lst e)
  (if (not lst) (return-from deletein nil))
  (if (= e (car lst))
    (deletein (cdr lst) e )
    (cons (car lst) (deletein (cdr lst) e) )
    )
  )
(setq x '(1 2 1 1))
(print (deletein x 1))
