(defun countin(lst e)
  (if (not lst) (return-from countin 0))
  (if (= e (car lst))
    (+ 1 (countin (cdr lst) e) )
    (+ 0 (countin (cdr lst) e) )
    )
  )
(setq x '(1 2 1 1))
(print (countin x 1))
